from fastapi import APIRouter, Query

from app.api.ingredients_schemas import (
    IngredientAutocompleteItem,
    IngredientAutocompleteResponse,
)
from app.models.schemas import ApiResponse
from app.service.ingredients import search_ingredients

router = APIRouter(prefix="/ingredients", tags=["ingredients"])

_INGREDIENT_SEEDS = [
    {"id": "ingredient-onion", "name": "양파"},
    {"id": "ingredient-green-onion", "name": "대파"},
    {"id": "ingredient-garlic", "name": "마늘"},
    {"id": "ingredient-carrot", "name": "당근"},
    {"id": "ingredient-potato", "name": "감자"},
    {"id": "ingredient-egg", "name": "계란"},
    {"id": "ingredient-tofu", "name": "두부"},
    {"id": "ingredient-kimchi", "name": "김치"},
    {"id": "ingredient-pork", "name": "돼지고기"},
    {"id": "ingredient-chicken", "name": "닭고기"},
    {"id": "ingredient-beef", "name": "소고기"},
    {"id": "ingredient-rice", "name": "밥"},
    {"id": "ingredient-ramen", "name": "라면"},
    {"id": "ingredient-tomato", "name": "토마토"},
    {"id": "ingredient-mushroom", "name": "버섯"},
    {"id": "ingredient-zucchini", "name": "애호박"},
    {"id": "ingredient-courgette", "name": "주키니"},
    {"id": "ingredient-cucumber", "name": "오이"},
    {"id": "ingredient-eggplant", "name": "가지"},
    {"id": "ingredient-napa-cabbage", "name": "배추"},
    {"id": "ingredient-cabbage", "name": "양배추"},
    {"id": "ingredient-lettuce", "name": "상추"},
    {"id": "ingredient-perilla-leaf", "name": "깻잎"},
    {"id": "ingredient-garlic-chive", "name": "부추"},
    {"id": "ingredient-spinach", "name": "시금치"},
    {"id": "ingredient-soybean-sprout", "name": "콩나물"},
    {"id": "ingredient-mung-bean-sprout", "name": "숙주"},
    {"id": "ingredient-broccoli", "name": "브로콜리"},
    {"id": "ingredient-paprika", "name": "파프리카"},
    {"id": "ingredient-bell-pepper", "name": "피망"},
    {"id": "ingredient-cheongyang-pepper", "name": "청양고추"},
    {"id": "ingredient-green-chili-pepper", "name": "풋고추"},
    {"id": "ingredient-red-chili-pepper", "name": "홍고추"},
    {"id": "ingredient-chili-pepper", "name": "고추"},
    {"id": "ingredient-radish", "name": "무"},
    {"id": "ingredient-young-radish", "name": "열무"},
    {"id": "ingredient-water-dropwort", "name": "미나리"},
    {"id": "ingredient-crown-daisy", "name": "쑥갓"},
    {"id": "ingredient-asparagus", "name": "아스파라거스"},
    {"id": "ingredient-celery", "name": "샐러리"},
    {"id": "ingredient-lotus-root", "name": "연근"},
    {"id": "ingredient-burdock-root", "name": "우엉"},
    {"id": "ingredient-sweet-potato", "name": "고구마"},
    {"id": "ingredient-sweet-pumpkin", "name": "단호박"},
    {"id": "ingredient-mature-pumpkin", "name": "늙은호박"},
    {"id": "ingredient-corn", "name": "옥수수"},
    {"id": "ingredient-green-pea", "name": "완두콩"},
    {"id": "ingredient-kidney-bean", "name": "강낭콩"},
    {"id": "ingredient-shiitake-mushroom", "name": "표고버섯"},
    {"id": "ingredient-king-oyster-mushroom", "name": "새송이버섯"},
    {"id": "ingredient-enoki-mushroom", "name": "팽이버섯"},
    {"id": "ingredient-oyster-mushroom", "name": "느타리버섯"},
    {"id": "ingredient-button-mushroom", "name": "양송이버섯"},
    {"id": "ingredient-wood-ear-mushroom", "name": "목이버섯"},
    {"id": "ingredient-apple", "name": "사과"},
    {"id": "ingredient-pear", "name": "배"},
    {"id": "ingredient-banana", "name": "바나나"},
    {"id": "ingredient-lemon", "name": "레몬"},
    {"id": "ingredient-lime", "name": "라임"},
    {"id": "ingredient-orange", "name": "오렌지"},
    {"id": "ingredient-avocado", "name": "아보카도"},
    {"id": "ingredient-pineapple", "name": "파인애플"},
    {"id": "ingredient-green-plum", "name": "매실"},
    {"id": "ingredient-pork-belly", "name": "삼겹살"},
    {"id": "ingredient-pork-neck", "name": "목살"},
    {"id": "ingredient-pork-shoulder", "name": "앞다리살"},
    {"id": "ingredient-pork-hind-leg", "name": "뒷다리살"},
    {"id": "ingredient-pork-ribs", "name": "돼지갈비"},
    {"id": "ingredient-ground-meat", "name": "다짐육"},
    {"id": "ingredient-bacon", "name": "베이컨"},
    {"id": "ingredient-ham", "name": "햄"},
    {"id": "ingredient-sausage", "name": "소시지"},
    {"id": "ingredient-chicken-breast", "name": "닭가슴살"},
    {"id": "ingredient-chicken-thigh", "name": "닭다리살"},
    {"id": "ingredient-chicken-wing", "name": "닭날개"},
    {"id": "ingredient-chicken-drumette", "name": "닭봉"},
    {"id": "ingredient-duck", "name": "오리고기"},
    {"id": "ingredient-beef-brisket-slice", "name": "차돌박이"},
    {"id": "ingredient-beef-belly-slice", "name": "우삼겹"},
    {"id": "ingredient-bulgogi-beef", "name": "불고기용소고기"},
    {"id": "ingredient-beef-brisket", "name": "양지"},
    {"id": "ingredient-beef-shank", "name": "사태"},
    {"id": "ingredient-shrimp", "name": "새우"},
    {"id": "ingredient-squid", "name": "오징어"},
    {"id": "ingredient-octopus", "name": "낙지"},
    {"id": "ingredient-webfoot-octopus", "name": "주꾸미"},
    {"id": "ingredient-giant-octopus", "name": "문어"},
    {"id": "ingredient-blue-crab", "name": "꽃게"},
    {"id": "ingredient-crab-stick", "name": "게맛살"},
    {"id": "ingredient-mussel", "name": "홍합"},
    {"id": "ingredient-manila-clam", "name": "바지락"},
    {"id": "ingredient-clam", "name": "조개"},
    {"id": "ingredient-oyster", "name": "굴"},
    {"id": "ingredient-abalone", "name": "전복"},
    {"id": "ingredient-anchovy", "name": "멸치"},
    {"id": "ingredient-dried-soup-anchovy", "name": "다시멸치"},
    {"id": "ingredient-mackerel", "name": "고등어"},
    {"id": "ingredient-hairtail", "name": "갈치"},
    {"id": "ingredient-salmon", "name": "연어"},
    {"id": "ingredient-tuna", "name": "참치"},
    {"id": "ingredient-frozen-pollock", "name": "동태"},
    {"id": "ingredient-pollock", "name": "명태"},
    {"id": "ingredient-half-dried-pollock", "name": "코다리"},
    {"id": "ingredient-fish-cake", "name": "어묵"},
    {"id": "ingredient-milk", "name": "우유"},
    {"id": "ingredient-cheese", "name": "치즈"},
    {"id": "ingredient-mozzarella-cheese", "name": "모짜렐라치즈"},
    {"id": "ingredient-cheddar-cheese", "name": "체다치즈"},
    {"id": "ingredient-butter", "name": "버터"},
    {"id": "ingredient-heavy-cream", "name": "생크림"},
    {"id": "ingredient-yogurt", "name": "요거트"},
    {"id": "ingredient-soy-milk", "name": "두유"},
    {"id": "ingredient-canned-tuna", "name": "참치캔"},
    {"id": "ingredient-spam", "name": "스팸"},
    {"id": "ingredient-imitation-crab", "name": "맛살"},
    {"id": "ingredient-dumpling", "name": "만두"},
    {"id": "ingredient-rice-cake", "name": "떡"},
    {"id": "ingredient-tteokbokki-rice-cake", "name": "떡볶이떡"},
    {"id": "ingredient-blood-sausage", "name": "순대"},
    {"id": "ingredient-fried-tofu-pouch", "name": "유부"},
    {"id": "ingredient-konjac", "name": "곤약"},
    {"id": "ingredient-short-grain-rice", "name": "쌀"},
    {"id": "ingredient-brown-rice", "name": "현미"},
    {"id": "ingredient-glutinous-rice", "name": "찹쌀"},
    {"id": "ingredient-barley", "name": "보리"},
    {"id": "ingredient-oat", "name": "귀리"},
    {"id": "ingredient-flour", "name": "밀가루"},
    {"id": "ingredient-pancake-mix", "name": "부침가루"},
    {"id": "ingredient-frying-mix", "name": "튀김가루"},
    {"id": "ingredient-starch", "name": "전분"},
    {"id": "ingredient-bread-crumbs", "name": "빵가루"},
    {"id": "ingredient-white-bread", "name": "식빵"},
    {"id": "ingredient-tortilla", "name": "또띠아"},
    {"id": "ingredient-pasta", "name": "파스타면"},
    {"id": "ingredient-spaghetti", "name": "스파게티면"},
    {"id": "ingredient-somen", "name": "소면"},
    {"id": "ingredient-wheat-noodle", "name": "중면"},
    {"id": "ingredient-udon-noodle", "name": "우동면"},
    {"id": "ingredient-kalguksu-noodle", "name": "칼국수면"},
    {"id": "ingredient-glass-noodle", "name": "당면"},
    {"id": "ingredient-rice-noodle", "name": "쌀국수면"},
    {"id": "ingredient-buckwheat-noodle", "name": "메밀면"},
    {"id": "ingredient-soy-sauce", "name": "간장"},
    {"id": "ingredient-dark-soy-sauce", "name": "진간장"},
    {"id": "ingredient-soup-soy-sauce", "name": "국간장"},
    {"id": "ingredient-brewed-soy-sauce", "name": "양조간장"},
    {"id": "ingredient-gochujang", "name": "고추장"},
    {"id": "ingredient-doenjang", "name": "된장"},
    {"id": "ingredient-ssamjang", "name": "쌈장"},
    {"id": "ingredient-chunjang", "name": "춘장"},
    {"id": "ingredient-oyster-sauce", "name": "굴소스"},
    {"id": "ingredient-tuna-sauce", "name": "참치액"},
    {"id": "ingredient-fish-sauce", "name": "액젓"},
    {"id": "ingredient-anchovy-fish-sauce", "name": "멸치액젓"},
    {"id": "ingredient-sand-lance-fish-sauce", "name": "까나리액젓"},
    {"id": "ingredient-salt", "name": "소금"},
    {"id": "ingredient-sugar", "name": "설탕"},
    {"id": "ingredient-oligosaccharide", "name": "올리고당"},
    {"id": "ingredient-corn-syrup", "name": "물엿"},
    {"id": "ingredient-honey", "name": "꿀"},
    {"id": "ingredient-vinegar", "name": "식초"},
    {"id": "ingredient-cooking-wine", "name": "맛술"},
    {"id": "ingredient-mirin", "name": "미림"},
    {"id": "ingredient-cooking-oil", "name": "식용유"},
    {"id": "ingredient-olive-oil", "name": "올리브유"},
    {"id": "ingredient-canola-oil", "name": "카놀라유"},
    {"id": "ingredient-sesame-oil", "name": "참기름"},
    {"id": "ingredient-perilla-oil", "name": "들기름"},
    {"id": "ingredient-chili-oil", "name": "고추기름"},
    {"id": "ingredient-mayonnaise", "name": "마요네즈"},
    {"id": "ingredient-ketchup", "name": "케첩"},
    {"id": "ingredient-mustard", "name": "머스터드"},
    {"id": "ingredient-pork-cutlet-sauce", "name": "돈가스소스"},
    {"id": "ingredient-steak-sauce", "name": "스테이크소스"},
    {"id": "ingredient-chili-sauce", "name": "칠리소스"},
    {"id": "ingredient-sriracha", "name": "스리라차"},
    {"id": "ingredient-hot-sauce", "name": "핫소스"},
    {"id": "ingredient-tomato-sauce", "name": "토마토소스"},
    {"id": "ingredient-cream-sauce", "name": "크림소스"},
    {"id": "ingredient-basil-pesto", "name": "바질페스토"},
    {"id": "ingredient-pepper", "name": "후추"},
    {"id": "ingredient-whole-peppercorn", "name": "통후추"},
    {"id": "ingredient-red-pepper-powder", "name": "고춧가루"},
    {"id": "ingredient-minced-garlic", "name": "다진마늘"},
    {"id": "ingredient-ginger", "name": "생강"},
    {"id": "ingredient-minced-ginger", "name": "다진생강"},
    {"id": "ingredient-sesame-seed", "name": "깨"},
    {"id": "ingredient-toasted-sesame-seed", "name": "통깨"},
    {"id": "ingredient-black-sesame-seed", "name": "검은깨"},
    {"id": "ingredient-perilla-seed-powder", "name": "들깨가루"},
    {"id": "ingredient-curry-powder", "name": "카레가루"},
    {"id": "ingredient-paprika-powder", "name": "파프리카가루"},
    {"id": "ingredient-cinnamon-powder", "name": "계피가루"},
    {"id": "ingredient-bay-leaf", "name": "월계수잎"},
    {"id": "ingredient-basil", "name": "바질"},
    {"id": "ingredient-parsley", "name": "파슬리"},
    {"id": "ingredient-oregano", "name": "오레가노"},
    {"id": "ingredient-rosemary", "name": "로즈마리"},
]


@router.get(
    "/autocomplete",
    response_model=ApiResponse[IngredientAutocompleteResponse],
    summary="재료 자동완성",
)
async def autocomplete_ingredients(
    q: str = Query("", description="검색 키워드"),
    limit: int = Query(10, ge=1, le=20, description="반환 제한 개수"),
) -> ApiResponse[IngredientAutocompleteResponse]:
    """재료 검색어를 받아 자동완성 후보를 공통 응답 형식으로 반환한다."""
    query = q.strip()
    if not query:
        # 빈 검색어는 오류가 아니라 후보 없음으로 처리해 프론트 입력 초기 상태를 단순하게 만든다.
        return ApiResponse(
            success=True,
            data=IngredientAutocompleteResponse(query=query, limit=limit, items=[]),
        )

    # 실제 매칭/정렬 책임은 service에 두어 라우터는 요청·응답 계약만 담당한다.
    matched_items = [
        IngredientAutocompleteItem(**ingredient)
        for ingredient in search_ingredients(_INGREDIENT_SEEDS, query, limit)
    ]

    return ApiResponse(
        success=True,
        data=IngredientAutocompleteResponse(
            query=query,
            limit=limit,
            items=matched_items,
        ),
    )
